const customLabelsConfig = {
    '2026': {
        'blank-lucario-mega': 'Mega Lucario',
        'blank-greninja': 'Greninja ex',
        'lopunny-mega-dusknoir': 'Mega Lopunny',
        'blank-slaking': 'Slaking',
        'gholdengo-typhlosion': 'Gholdengo',
        'sharpedo-mega-toxtricity': 'Mega Sharpedo Toxtricity',
        'kangaskhan-mega-forretress': 'Mega Kangaskhan',
        'blank-palafin-hero': 'Palafin',
        'ursaluna-bloodmoon-lunatone': 'Ursaluna Lunatone',
        'ogerpon-meganium': 'Meganium',
        'venusaur-mega-meganium': 'Mega Venusaur',
        'absol-mega-kangaskhan-mega': 'Mega Absol Box',
        'kangaskhan-mega-bouffalant': 'Mega Kangaskhan',
        'blank-kangaskhan-mega': 'Mega Kangaskhan',
        'gholdengo-lunatone': 'Gholdengo Lunatone',
        'lucario-mega-hariyama': 'Lucario Hariyama',
        'alakazam-dudunsparce': 'Alakazam',
        'manectric-mega-eelektrik': 'Mega Manectric Eels',
        'blank-gardevoir': 'Gardevoir ex',
        'gardevoir-jellicent': 'Gardevoir ex',
        'chien-pao-baxcalibur': 'Chien-Pao Baxcalibur',
        'raging-bolt-ogerpon': 'Raging Bolt',
        'blank-miraidon': 'Miraidon',
        'dragapult-pidgeot': 'Dragapult Pidgeot',
        'dragapult-blaziken': 'Dragapult Blaziken',
        'blank-dragapult': 'Dragapult',
        'blank-conkeldurr': 'Conkeldurr',
        'blank-crustle': 'Crustle',
        'blank-pidgeot': 'Pidgeot Control',
        'iron-hands-iron-crown': 'Future Box',
        'blank-roaring-moon': 'Roaring Moon',
        'roaring-moon-dudunsparce': 'Roaring Moon',
        'charizard-pidgeot': 'Charizard Pidgeot',
        'charizard-bibarel': 'Charizard Bibarel',
        'charizard-noctowl': 'Charizard Noctowl',
        'dragapult-charizard': 'Dragapult Charizard',
        'blank-great-tusk': 'Great Tusk Mill',
        'blank-ironthorns': 'Iron Thorns',
        'gholdengo-palkia-origin': 'Gholdengo',
        'gholdengo-scizor': 'Gholdengo Scizor',
        'gholdengo-dragapult': 'Gholdengo Dragapult',
        'gholdengo-joltik': 'Gholdengo',
        'dragapult-xatu': 'Dragapult Xatu',
        'roaring-moon-koraidon': 'Ancient Box',
        'roaring-moon-great-tusk': 'Ancient Box',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'murkrow-flamigo': 'United Wings',
        'froslass-munkidori': 'Froslass',
        'espathra-froslass': 'Espathra Froslass',
        'raging-bolt-sandy-shocks': 'Raging Bolt Sandy Shocks',
        'klawf-brute-bonnet': 'Klawf',
        'archaludon-brute-bonnet': 'Poison Archaludon',
        'espathra-xatu': 'Espathra',
        'koraidon-roaring-moon': 'Ancient Box',
        'blank-gouging-fire': 'Gouging Fire',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'roaring-moon-darkrai': 'Roaring Moon',
        'ogerpon-cornerstone-noivern': 'Cornerstone Ogerpon Noivern',
        'banette-dusknoir': 'Banette Dusknoir',
        'charizard-dusknoir': 'Charizard Dusknoir',
        'iron-valiant-ursaluna-bloodmoon': 'Iron Valiant Ursaluna',
        'joltik-pikachu': 'Joltik Box',
        'flareon-noctowl': 'Flareon ex',
        'noctowl-ogerpon-wellspring': 'Tera Box',
        'blank-gholdengo': 'Gholdengo',
        'dragapult-dusknoir': 'Dragapult Dusknoir',
        'blank-archaludon': 'Archaludon',
        'blank-copperajah': 'Copperajah ex',
        'blank-slowking': 'Slowking',
        'milotic-farigiraf': 'Milotic',
        'blank-hydreigon': 'Hydreigon ex',
        'blank-mamoswine': 'Mamoswine ex',
        'blank-feraligatr': 'Feraligatr',
        'clefairy-noctowl': 'Lillie\'s Clefairy Box',
        'terapagos-noctowl': 'Terapagos',
        'okidogi-dudunsparce': 'Okidogi',
        'okidogi-garchomp': 'Okidogi Garchomp',
        'blank-okidogi': 'Okidogi',
        'blank-zoroark': 'N\'s Zoroark',
        'blaziken-zoroark': 'N\'s Zoroark',
        'dragapult-zoroark': 'Dragapult N\'s Zoroark',
        'toedscruel-ogerpon': 'Toadscruel',
        'blank-garchomp': 'Cynthia\'s Garchomp',
        'blank-ceruledge': 'Ceruledge',
        'spidops-mewtwo': 'Team Rocket\'s Mewtwo',
        'ho-oh-armarouge': 'Ho-Oh Armarouge',
        'blank-typhlosion': 'Ethan\'s Typhlosion',
        'ogerpon-ogerpon-wellspring': 'Ogerpon Box',
        'iron-leaves-iron-crown': 'Future Box',
        'blank-blissey': 'Blissey ex',
        'dipplin-thwackey': 'Festival Lead',
        'joltik-miraidon': 'Joltik Box',
        'tinkaton-dudunsparce': 'Tinkaton',
        'grimmsnarl-froslass': 'Marnie\'s Grimmsnarl',
        'blank-grimmsnarl': 'Marnie\'s Grimmsnarl',
        'magmortar-volcanion': 'Magmortar Volcanion',
        'zacian-crowned-snorlax': 'Hop\'s Zacian',
        'blank-substitute': 'Other',
        'klawf-terapagos': 'Klawf Terapagos',
    },
    '2025': {
        'blank-gardevoir': 'Gardevoir ex',
        'gardevoir-jellicent': 'Gardevoir ex',
        'chien-pao-baxcalibur': 'Chien-Pao Baxcalibur',
        'lugia-archeops': 'Lugia Archeops',
        'raging-bolt-ogerpon': 'Raging Bolt',
        'blank-miraidon': 'Miraidon',
        'arceus-vulpix-alola': 'Arceus Vulpix',
        'miraidon-regieliki-vmax': 'Miraidon Regieliki',
        'blank-snorlax': 'Snorlax Stall',
        'dragapult-pidgeot': 'Dragapult Pidgeot',
        'blank-dragapult': 'Dragapult',
        'dragapult-comfey': 'Dragapult LZB',
        'blank-comfey': 'Lost Box',
        'blank-pidgeot': 'Pidgeot Control',
        'palkia-origin-noctowl': 'Palkia Noctowl',
        'regidrago-ogerpon': 'Regidrago',
        'comfey-sableye': 'Lost Box',
        'iron-hands-iron-crown': 'Future Box',
        'blank-roaring-moon': 'Roaring Moon',
        'roaring-moon-dudunsparce': 'Roaring Moon',
        'goodra-hisui-comfey': 'Goodra LZB',
        'charizard-pidgeot': 'Charizard Pidgeot',
        'charizard-bibarel': 'Charizard Bibarel',
        'charizard-noctowl': 'Charizard Noctowl',
        'blank-regigigas': "Regis",
        'dragapult-charizard': 'Dragapult Charizard',
        'blank-great-tusk': 'Great Tusk Mill',
        'blank-ironthorns': 'Iron Thorns',
        'gholdengo-palkia-origin': 'Gholdengo',
        'gholdengo-scizor': 'Gholdengo Scizor',
        'gholdengo-dragapult': 'Gholdengo Dragapult',
        'gholdengo-joltik': 'Gholdengo',
        'dragapult-xatu': 'Dragapult Xatu',
        'dialga-origin-metang': 'Dialga VSTAR',
        'roaring-moon-koraidon': 'Ancient Box',
        'roaring-moon-great-tusk': 'Ancient Box',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'murkrow-flamigo': 'United Wings',
        'froslass-munkidori': 'Froslass',
        'espathra-froslass': 'Espathra Froslass',
        'raging-bolt-sandy-shocks': 'Raging Bolt Sandy Shocks',
        'klawf-brute-bonnet': 'Klawf',
        'klawf-terapagos': 'Klawf Terapagos',
        'terapagos-palkia-origin': 'Terapagos Palkia',
        'archaludon-brute-bonnet': 'Poison Archaludon',
        'giratina-origin-comfey': 'Giratina LZB',
        'arceus-giratina-origin': 'Arceus Giratina',
        'comfey-roaring-moon': 'Lost Box',
        'arceus-armarouge': 'Arceus Armarouge',
        'arceus-charizard-shiny': 'Arceus Radiant Zard',
        'espathra-xatu': 'Espathra',
        'koraidon-roaring-moon': 'Ancient Box',
        'banette-gardevoir': 'Banette Gardevoir ex',
        'blank-gouging-fire': 'Gouging Fire',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'roaring-moon-darkrai': 'Roaring Moon',
        'palkia-origin-chien-pao': 'Palkia VSTAR',
        'comfey-charizard-shiny': 'Radiant Charizard LZB',
        'ogerpon-cornerstone-noivern': 'Cornerstone Ogerpon Noivern',
        'arceus-dusknoir': 'Arceus Dusknoir',
        'palkia-origin-dusknoir': 'Palkia Dusknoir',
        'banette-dusknoir': 'Banette Dusknoir',
        'charizard-dusknoir': 'Charizard Dusknoir',
        'iron-valiant-ursaluna-bloodmoon': 'Iron Valiant Ursaluna',
        'joltik-pikachu': 'Joltik Box',
        'flareon-noctowl': 'Flareon ex',
        'noctowl-ogerpon-wellspring': 'Tera Box',
        'blank-gholdengo': 'Gholdengo',
        'dragapult-dusknoir': 'Dragapult Dusknoir',
        'blank-archaludon': 'Archaludon',
        'blank-copperajah': 'Copperajah ex',
        'blank-slowking': 'Slowking',
        'milotic-farigiraf': 'Milotic',
        'blank-hydreigon': 'Hydreigon ex',
        'blank-mamoswine': 'Mamoswine ex',
        'blank-feraligatr': 'Feraligatr',
        'clefairy-noctowl': 'Lillie\'s Clefairy Box',
        'terapagos-noctowl': 'Terapagos',
        'okidogi-dudunsparce': 'Okidogi',
        'okidogi-garchomp': 'Okidogi Garchomp',
        'blank-okidogi': 'Okidogi',
        'blank-zoroark': 'N\'s Zoroark',
        'blaziken-zoroark': 'N\'s Zoroark',
        'dragapult-zoroark': 'Dragapult N\'s Zoroark',
        'toedscruel-ogerpon': 'Toadscruel',
        'blank-garchomp': 'Cynthia\'s Garchomp',
        'blank-ceruledge': 'Ceruledge',
        'spidops-mewtwo': 'Team Rocket\'s Mewtwo',
        'ho-oh-armarouge': 'Ho-Oh Armarouge',
        'blank-typhlosion': 'Ethan\'s Typhlosion',
        'ogerpon-ogerpon-wellspring': 'Ogerpon Box',
        'iron-leaves-iron-crown': 'Future Box',
        'blank-blissey': 'Blissey ex',
        'dipplin-thwackey': 'Festival Lead',
        'joltik-miraidon': 'Joltik Box',
        'tinkaton-dudunsparce': 'Tinkaton',
        'grimmsnarl-froslass': 'Marnie\'s Grimmsnarl',
        'magmortar-volcanion': 'Magmortar Volcanion',
        'zacian-crowned-snorlax': 'Hop\'s Zacian',
        'blank-substitute': 'Other',
    },
    '2024': {
        'blank-gardevoir': 'Gardevoir ex',
        'chien-pao-baxcalibur': 'Chien-Pao Baxcalibur',
        'comfey-sableye': 'Lost Box',
        'lugia-archeops': 'Lugia Archeops',
        'raging-bolt-ogerpon': 'Raging Bolt',
        'blank-miraidon': 'Miraidon',
        'blank-snorlax': 'Snorlax Stall',
        'dragapult-pidgeot': 'Dragapult Pidgeot',
        'blank-dragapult': 'Dragapult',
        'dragapult-comfey': 'Dragapult LZB',
        'blank-pidgeot': 'Pidgeot Control',
        'regidrago-ogerpon': 'Regidrago',
        'iron-hands-iron-crown': 'Future Box',
        'blank-roaring-moon': 'Roaring Moon',
        'roaring-moon-dudunsparce': 'Roaring Moon',
        'charizard-pidgeot': 'Charizard Pidgeot',
        'charizard-bibarel': 'Charizard Bibarel',
        'dragapult-charizard': 'Dragapult Charizard',
        'blank-ironthorns': 'Iron Thorns',
        'gholdengo-palkia-origin': 'Gholdengo',
        'gholdengo-scizor': 'Gholdengo Scizor',
        'dragapult-xatu': 'Dragapult Xatu',
        'dialga-origin-metang': 'Dialga VSTAR',
        'roaring-moon-koraidon': 'Ancient Box',
        'roaring-moon-great-tusk': 'Ancient Box',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'froslass-munkidori': 'Froslass',
        'raging-bolt-sandy-shocks': 'Raging Bolt Sandy Shocks',
        'klawf-brute-bonnet': 'Klawf',
        'giratina-origin-comfey': 'Giratina LZB',
        'arceus-giratina-origin': 'Arceus Giratina',
        'comfey-roaring-moon': 'Lost Box',
        'arceus-armarouge': 'Arceus Armarouge',
        'arceus-charizard-shiny': 'Arceus Radiant Zard',
        'espathra-xatu': 'Espathra',
        'koraidon-roaring-moon': 'Ancient Box',
        'banette-gardevoir': 'Banette Gardevoir ex',
        'tinkaton-dudunsparce': 'Tinkaton',
        'palkia-origin-chien-pao': 'Palkia VSTAR',
        'comfey-charizard-shiny': 'Radiant Charizard LZB',
        'feraligatr-palkia-origin': 'Feraligatr',
        'blank-great-tusk': 'Great Tusk Mill',
        'arceus-vulpix-alola': 'Arceus Vulpix',
        'roaring-moon-darkrai': 'Roaring Moon',
        'miraidon-regieliki-vmax': 'Miraidon',
        'armarouge-chi-yu': 'Armarouge Box',
        'blank-gouging-fire': 'Gouging Fire',
        'roaring-moon-flutter-mane': 'Ancient Box',
        'mew-vmax-genesect': 'Mew VMAX',
        'entei-iron-valiant': 'Entei Iron Valiant',
        'urshifu-rapid-strike-gmax-inteleon-vmax': 'Rapid Strike',
        'blank-zoroark': 'Zoroark Box',
        'murkrow-flamigo': 'United Wings',
    },
    '2023': {
        'comfey-charizard-shiny': 'Radiant Charizard LZB',
        'comfey-sableye': 'Lost Box',
        'mew-vmax-genesect': 'Mew VMAX',
        'blank-gardevoir': 'Gardevoir ex',
        'lugia-archeops': 'Lugia Archeops',
        'giratina-origin-comfey': 'Giratina LZB',
        'arceus-giratina-origin': 'Arceus Giratina',
        'chien-pao-baxcalibur': 'Chien Pao Baxcalibur',
        'arceus-umbreon-vmax': 'Arceus Umbreon',
        'palkia-origin-chien-pao': 'Palkia Chien Pao',
        'urshifu-rapid-strike-gmax-inteleon-vmax': 'Rapid Strike',
        'blank-miraidon': 'Miraidon',
        'goodra-hisui-comfey': 'Goodra LZB',
        'arceus-regidrago': 'Arceus Regidrago',
        'arceus-goodra-hisui': 'Arceus Goodra',
        'miraidon-regieliki-vmax': 'Miraidon',
        'arceus-aggron-vmax': 'Arceus Aggron',
        'vulpix-alola-yveltal': 'Sander Box',
        'blank-inteleon-vmax': 'Rapid Strike',
        'duraludon-gmax-arceus': 'Arceus Duraludon',
        'arceus-aerodactyl': 'Arceus Aerodactyl',
        'inteleon-vmax-urshifu-rapid-strike-gmax': 'Rapid Strike',
        'blank-darkrai': 'Darkrai VSTAR',
        'murkrow-flamigo': 'United Wings',
        'arceus-regidrago': 'Arceus Regidrago',
        'gardevoir-mewtwo': 'Gardevoir ex',
        'arceus-duraludon-gmax': 'Arceus Duraludon',
        'blank-zoroark': 'Zoroark Box',
        'arceus-pikachu-gmax': 'Arceus Flying Pikachu',
        'palkia-origin-gardevoir': 'Palkia Gardevoir',
        'ting-lu-koraidon': 'Ting-Lu Koraidon',
        'arceus-vulpix-alola': 'Arceus Vulpix',
        'ursaluna-mimikyu': 'Sander Box',
        'charizard-shiny-comfey': 'Radiant Charizard LZB',
        'lugia-duraludon-gmax': 'Lugia Archeops',
        'yveltal-eldegoss': "Yveltal Control",
        'blank-regigigas': "Regis",
        'blank-vikavolt': "Vikavolt",
        'articuno-inteleon': "Articuno Inteleon",
        'palkia-origin-inteleon': 'Palkia Inteleon',
        'sableye-comfey': 'Lost Box',
        'kyurem-vmax-palkia-origin': 'Kyurem VMAX',
        'comfey-rayquaza': 'LZB Amazing Rayquaza',
        'blissey-yveltal': 'Blissey',
    },
    '2022': {
        'palkia-origin-inteleon': 'Palkia Inteleon',
        'arceus-pikachu-gmax': 'Arceus Flying Pikachu',
        'palkia-origin-calyrex-ice-rider': 'Palkia Ice Rider',
        'mew-vmax-genesect': 'Mew VMAX',
        'palkia-origin-jolteon': 'Palkia Jolteon',
        'arceus-inteleon': 'Arceus Inteleon',
        'charizard-shiny-inteleon': 'Radiant Charizard Inteleon',
        'blank-regigigas': 'Regis',
        'arceus-aggron-vmax': 'Arceus Aggron',
        'arceus-duraludon-gmax': 'Arceus Duraludon',
        'vikavolt-moltres-galar': 'Vikavolt Moltres',
        'arceus-lucario': 'Arceus Lucario',
        'mewtwo-snorlax': 'Mewtwo V-UNION',
        'calyrex-ice-rider-inteleon': 'Ice Rider',
        'blank-stonjourner': 'Stonjourner VMAX',
        'urshifu-rapid-strike-gmax-inteleon': 'Rapid Strike Urshifu Inteleon',
        'arceus-mewtwo': 'Arceus Mewtwo V-UNION',
        'arceus-beedrill': 'Arceus Beedrill',
        'blank-whimsicott': 'Whimsicott VSTAR',
        'malamar-inteleon': 'Malamar (Rapid Strike)',
        'arceus-lycanroc-dusk': 'Arceus Lycanroc',
        'arceus-crobat-vmax': 'Arceus Crobat VMAX',
        'arceus-urshifu-rapid-strike-gmax': 'Arceus Urshifu',
        'umbreon-vmax-eldegoss': 'Umbreon Stall',
        'arceus-malamar-vmax': 'Arceus Malamar VMAX',
        'arceus-sylveon-vmax': 'Arceus Rapid Strike',
        'arceus': 'Arceus Melony',
        'moltres-galar-inteleon': 'Moltres Inteleon',
        'calyrex-shadow-rider-whimsicott': 'Shadow Rider',
        'suicune-ludicolo': 'Suicune Ludicolo',
        'arceus-whimsicott': 'Arceus Whimsicott',
        'mewtwo-miltank': 'Mewtwo V-UNION',
        'palkia-origin': 'Palkia VSTAR',
        'blissey-miltank': 'Blissey',
        'palkia-origin-ditto': 'Palkia VSTAR',
        'miltank-cinccino': 'Miltank Stall',
    },
    '2021': {

    },
    '2020': {
        'adp-zacian-crowned': 'ADP',
        'blank-pikachu-zekrom-tagteam': 'PikaRom',
        'mewtwo-mew-tagteam-malamar': 'Mewtwo & Mew + Malamar',
        'blank-mewtwo-mew-tagteam': 'Mewtwo & Mew',
        'blank-blacephalon': 'Baby Blowns',
        'oranguru-cinccino': 'Oranguru Mill',
        'malamar-giratina': 'Malamar',
        'blank-magcargo': 'Magcargo GX',
        'reshiram-charizard-tagteam-ninetales': 'ReshiZard',
        'blank-reshiram-charizard-tagteam': 'ReshiZard',
        'blank-obstagoon': 'Obstagoon',
        'magcargo-oranguru': 'Magcargo Mill',
        'lucario-melmetal-tagteam-zacian-crowned': 'LucMetal Zacian',
        'oranguru-pidgeotto': 'Pidgeotto Control',
        'adp-keldeo': 'ADP',
        'blank-adp': 'ADP',
        'blacephalon-pidgeotto': 'Baby Blowns',
        'blacephalon-naganadel': 'Blacephalon Naganadel',
        'florges-munchlax': 'Florges Stall',
        'guzzlord-naganadel-tagteam-mismagius': 'Guzzlord & Naganadel',
        'giratina-garchomp-tagteam-mismagius': 'Giratina & Garchomp',
        'gardevoir-sylveon-tagteam-omastar': 'Gardevoir & Sylveon',
        'charizard-braixen-tagteam-volcanion': 'Charizard & Braixen',
        'silvally-quagsire': 'Silvally GX',
        'gardevoir-sylveon-tagteam-xerneas-active': 'Gardevoir & Sylveon',
        'mewtwo-mew-tagteam-victini': 'Mewtwo & Mew',
        'quagsire-naganadel': 'QuagNag',
        'blank-charizard-braixen-tagteam': 'Charizard & Braixen',
    },
    '2019': {
        'blank-pikachu-zekrom-tagteam': 'PikaRom',
        'blank-reshiram-charizard-tagteam': 'ReshiZard',
        'blank-mewtwo-mew-tagteam': 'Mewtwo & Mew',
        'reshiram-charizard-tagteam-volcanion-right': 'GreensZard',
        'oranguru-pidgeotto': 'Pidgeotto Control',
        'gardevoir-sylveon-tagteam-xerneas-active': 'Gardevoir & Sylveon',
        'blacephalon-naganadel': 'Blacephalon Naganadel',
        'malamar-giratina': 'Malamar',
        'blank-gardevoir-sylveon-tagteam': 'Gardevoir & Sylveon',
        'malamar-necrozma-ultra': 'Malamar',
        'malamar-necrozma': 'Malamar',
        'blacephalon-persian': 'Blacephalon GX',
        'weavile-naganadel': 'Dark Box',
        'keldeo-bronzong': 'Wall Stall',
        'blacephalon-volcanion': 'Blacephalon GX',
        'gardevoir-sylveon-tagteam-mismagius': 'Gardevoir & Sylveon',
        'blank-spiritomb': 'Spiritomb',
        'gengar-mimikyu-tagteam-omastar': 'MimiGar Omastar',
        'blank-giratina-garchomp-tagteam': 'Giratina & Garchomp',
        'blank-exeggutor-alola-rowlet-tagteam': 'RowEggs',
        'mewtwo-mew-tagteam-blastoise': 'Mewtwo & Mew (Water)',
        'rampardos-omastar': 'Fossils',
        'quagsire-naganadel': 'QuagNag',
        'spiritomb-umbreon': 'Spiritomb',
        'hoopa-unbound-regigigas': 'Wall Stall',
        'zoroark-dewgong': 'Checkmate',
        'pikachu-zekrom-tagteam-zapdos': 'PikaRom Zapdos',
        'zapdos-buzzwole': 'ZapBeasts',
        'reshiram-charizard-tagteam-snorlax-eevee-tagteam': 'ReshiZard',
        'blank-blacephalon': 'Baby Blowns',
        'zoroark-persian': 'Zoroark Persian',
        'blank-weezing': 'Weezing',
        'blank-zapdos': 'Zapdos',
        'lucario-melmetal-tagteam-vileplume': 'LucMetal Vileplume',
        'spiritomb-stunfisk': 'Spiritomb',
        'reshiram-charizard-tagteam-volcanion': 'GreensZard',
        'blank-blissey': 'Blissey',
        'nidoqueen-meganium': 'Nidoqueen Meganium',
        'gardevoir-ninetales-alola': 'Gardevoir GX',
        'zoroark-silvally': 'Zoroark Silvally',
        'blank-doublade': 'Doublade',
        'zoroark-lycanroc-midnight': 'Zoroark Lycanroc',
        'hoopa-unbound-lucario-melmetal-tagteam': 'Wall Stall',
        'zapdos-jolteon': 'Zapdos',
        'rayquaza-vikavolt': 'Rayquaza GX',
        'blank-tapu-koko': 'Tapu Koko Spread',
        'stakataka-naganadel': 'Ultra Beasts',
        'zapdos-lycanroc-midnight': 'Zapdos',
        "tapu-koko-greninja": 'Tapu Koko Spread',
        'zapdos-lucario': 'Zapdos',
        'buzzwole-weavile': 'Buzzwole Weavile',
        'blank-venusaurcelebi': 'Celebi & Venusaur',
        'shedinja-oranguru': 'Sheninja Control',
        'regigigas-hoopa-unbound': 'Wall Stall',
        'zoroark-oranguru': 'Zoroark Control',
        'passimian-tapu-koko': 'Passimian',
        'jumpluff-weavile': 'Lost March',
        'buzzwole-lycanroc-midnight': 'Buzzwole Lycanroc',
        'blank-granbull': 'Granbull',
        'malamar-tapu-koko': 'Malamar',
        'zoroark-decidueye': 'Zoroark Decidueye',
        'zoroark-ninetales-alola': 'Zoroark Ninetales',
        'gardevoir-swampert': 'Gardevoir GX',
        'zoroark-glaceon': 'Zoroark Glaceon',
        'buzzwole-ninetales-alola': 'Buzzwole Ninetales',
        'steelix-hoopa-unbound': 'Wall Stall',
        'zoroark-weavile': 'Zoroark Weavile',
        'decidueye-ninetales-alola': 'Decidueye Ninetales',
        'regigigas-genesect': 'Wall Stall',
        'zoroark-buzzwole': 'Zoroark Buzzwole',
        'jumpluff-natu': 'Lost March',
        'exeggutor-alola-grovyle': 'Tropical Shake',
        'malamar-marshadow': 'Malamar',
    },
    '2018': {
        'zoroark-garbodor': 'Zoroark Garbodor',
        'blank-rayquaza': 'Rayquaza GX',
        'buzzwole-garbodor': 'Buzzwole Garbodor',
        'blank-greninja': 'Greninja',
        'buzzwole-lycanroc-midnight': 'Buzzwole Lycanroc',
        'zoroark-gallade': 'Zoroark Gallade',
        'malamar-necrozma': 'Malamar',
        'zygarde-complete-lycanroc-midnight': 'Zygarde GX',
        'zoroark-golisopod': 'Zoroark Golisopod',
        'banette-garbodor': 'Banette Garbodor',
        'buzzwole-magcargo': 'Buzzwole',
        'zoroark-lycanroc-midnight': 'Zoroark Lycanroc',
        'malamar-hoopa-unbound': 'Malamar',
        'yveltal-hoopa-unbound': 'Yveltal BREAK',
        'blank-yveltal': 'Yveltal BREAK',
        'golisopod-garbodor': 'Golisopod Garbodor',
        'naganadel-stakataka': 'Ultra Beasts',
        'malamar-necrozma-ultra': 'Malamar',
        'blank-zoroark': 'Zoroark',
        'blank-hoopa-unbound': 'Hoopa',
        'blank-sylveon': 'Sylveon GX',
        'malamar-lugia-shiny': 'Malamar',
        'necrozma-dusk-mane-magnezone': 'Dusk Mane Magnezone',
        'blank-buzzwole': 'Buzzwole GX',
        'blank-volcanion': 'Volcanion',
        'blank-lapras': 'Lapras',
        'buzzwole-lucario': 'Buzzwole GX',
        'zoroark-mewtwo': 'Zoroark Mewtwo',
        'malamar-marshadow': 'Malamar',
        'zoroark-lucario': 'Zoroark Lucario',
        'tapu-bulu-vikavolt': 'VikaBulu',
        'espeon-garbodor': 'Espeon Garbodor',
        'lucario-buzzwole': 'Lucario GX',
        'gardevoir-talonflame': 'Gardevoir GX',
        'zoroark-glaceon': 'Zoroark Glaceon',
        'lurantis-tapu-bulu': 'Lurantis',
        'blank-ho-oh': 'Ho-Oh GX',
        'lucario-lycanroc-midnight': 'Lucario GX',
        'lucario-garbodor': 'Lucario GX',
        'zoroark-magnezone': 'Zoroark Magnezone',
        'zoroark-gardevoir': 'Zoroark Gardevoir',
        'gardevoir-sylveon': 'Gardevoir GX',
        'blank-gardevoir': 'Gardevoir GX',
        'blank-xerneas-active': 'Xerneas BREAK',
        'wishiwashi-school-hoopa-unbound': 'Wall Stall',
        'decidueye-zoroark': 'Decidueye Zoroark',
        'silvally-zoroark': 'Silvally GX',
        'drampa-garbodor': 'Drampa Garbodor',
        'silvally-registeel': 'Silvally Metal Box',
        'blank-metagross': 'Metagross GX',
        'heatmor-raichu': 'Heatmor Raichu',
        'zoroark-drampa': 'Zoroark BREAK',
        'buzzwole-silvally': 'Buzzwole GX',
        'volcanion-silvally': 'Volcanion',
        'zoroark-bisharp': 'Zoroark GX',
        'zoroark-buzzwole': 'Zoroark Buzzwole',
        'genesect-zoroark': 'Metal Box',
        'tapu-koko-meowstic': 'Tapu Koko Spread',
        'registeel-scizor': 'Metal Box',
        'gardevoir-xerneas-active': 'Gardevoir GX',
    },
    '2017': {
        'drampa-garbodor': 'Drampa Garbodor',
        'espeon-garbodor': 'Espeon Garbodor',
        'blank-gardevoir': 'Gardevoir GX',
        'golisopod-garbodor': 'Golisopod Garbodor',
        'volcanion-turtonator': 'Volcanion',
        'blank-rayquaza-mega': 'Mega Rayquaza',
        'ho-oh-salazzle': 'Ho-Oh Salazzle',
        'garbodor-necrozma': 'Garbodor Spread',
        'decidueye-vileplume': 'Decidueye Vileplume',
        'blank-greninja': 'Greninja',
        'gardevoir-sylveon': 'Gardevoir GX',
        'decidueye-ninetales-alola': 'Decidueye Ninetales',
        'blank-ninetales-alola': 'Alolan Ninetales',
        'gardevoir-xerneas-active': 'Gardevoir GX',
        'golisopod-decidueye': 'Golisopod Decidueye',
        'xerneas-active-bisharp': 'Rainbow Road',
        'zoroark-drampa': 'Zoroark BREAK',
        'tapu-bulu-vikavolt': 'VikaBulu',
        'blank-volcanion': 'Volcanion',
        'blank-gardevoir-mega': 'Mega Gardevoir Brilliant Arrow',
        'gardevoir-mega-xerneas-active': 'Mega Gardevoir Brilliant Arrow',
        'blank-gardevoir-mega-shiny': 'Mega Gardevoir Despair Ray',
        'blank-decidueye': 'Decidueye',
        'blank-metagross': 'Metagross',
        'zoroark-garbodor': 'Zoroark Garbodor',
        'darkrai-giratina-origin': 'Darkrai',
        'darkrai-garbodor': 'Darkrai',
        'blank-darkrai': 'Darkrai',
        'darkrai-dragonair': 'Darkrai',
        'blank-groudon-primal': 'Primal Groudon',
        'blank-xerneas-active': 'Rainbow Road',
        'yveltal-garbodor': 'Yveltal Garbodor',
        'blank-mewtwo-mega-y': 'Mega Mewtwo',
        'blank-vespiquen': 'Vespiquen',
        'mewtwo-mega-y-garbodor': 'Mega Mewtwo',
        'houndoom-raticate': 'Houndoom Mill',
        'jolteon-garbodor': 'Jolteon Garbodor',
        'blank-gyarados': 'Gyarados',
        'zygarde-complete-carbink': 'Zygarde Carbink',
        'yveltal-zoroark': 'Yveltal Zoroark',
        'zoroark-yveltal': 'Yveltal Zoroark',
        'vespiquen-raichu': 'Vespiquen',
        'xerneas-active-salamence': 'Xerneas BREAK',
        'rayquaza-mega-raichu': 'Mega Rayquaza',
        'blank-yveltal': 'Yveltal',
        'alakazam-mega-espeon': 'Mega Alakazam',
    },
    '2016': {
        'joltik-pumpkaboo': 'Night March',
        'blank-greninja': 'Greninja',
        'bronzong-aegislash': 'Metal Box',
        'seismitoad-manaphy': 'Water Box',
        'blank-audino-mega': 'Mega Audino',
        'blank-volcanion': 'Volcanion',
        'vespiquen-vileplume': 'Vespiquen Vileplume',
        'vileplume-jolteon': 'Plume Box',
        'yveltal-vespiquen': 'Yveltal Vespiquen',
        'joltik-vespiquen': 'Night March Vespiquen',
        'bronzong-genesect': 'Metal Box',
        'vespiquen-excadrill': 'Vespiquen',
        'zygarde-complete-vileplume': 'Zygarde Vileplume',
        'blank-sceptile-mega': 'Mega Sceptile',
        'yanmega-vespiquen': 'Yanmega BREAK',
        'seismitoad-crobat': 'Toad Bats',
        'blank-trevenant': 'Trevenant BREAK',
        'manectric-mega-garbodor': 'Mega Manectric Garbodor',
        'yveltal-zoroark': 'Yveltal Zoroark',
        'darkrai-giratina-origin': 'Darkrai Giratina',
        'zygarde-complete-carbink': 'Zygarde Carbink',
        'blank-manectric-mega': 'Mega Manectric',
        'blank-medicham': 'Medicham',
        'seismitoad-giratina-origin': 'Seismitoad Giratina',
        'vespiquen-zoroark': 'Vespiquen',
        'blank-vespiquen': 'Vespiquen',
        'blank-rayquaza-mega': 'Mega Rayquaza',
        'aromatisse-seismitoad': 'Fairy Box',
        'bronzong-tyrantrum': 'Metal Dragons',
        'manectric-mega-ho-oh': 'Mega Manectric Ho-Oh',
        'houndoom-bunnelby': 'Houndoom Mill',
    },
    '2015': {
        'joltik-pumpkaboo': 'Night March',
        'blastoise-keldeo-resolute': 'ArchieStoise',
        'trevenant-gengar': 'Trevenant Gengar',
        'seismitoad-manectric': 'Toad Bats',
        'raichu-crobat': 'Raichu Bats',
        'seismitoad-crobat': 'Toad Bats',
        'blank-donphan': 'Donphan',
        'aegislash-bronzong': 'Metal Box',
        'aromatisse-seismitoad': 'Fairy Box',
        'groudon-primal-wobbuffet': 'Primal Groudon',
        'manectric-mega-genesect': 'Mega Manectric (Plasma)',
        'landorus-therian-crobat': 'Landy Bats',
        'manectric-mega-yanmega': 'Mega Manectric Yanmega',
        'seismitoad-garbodor': 'Seismitoad Garbodor',
        'blank-groudon-primal': 'Primal Groudon',
        'manectric-mega-keldeo-resolute': 'Mega Manectric',
        'klinklang-bronzong': 'Klinklang',
        'manectric-mega-terrakion': 'Mega Manectric',
        'landorus-therian-leafeon': 'Landorus-EX',
        'blank-manectric-mega': 'Mega Manectric',
        'rayquaza-mega-bronzong': 'Mega Rayquaza Bronzong',
        'bronzong-aegislash': 'Metal Box',
        'blank-wailord': 'Wailord Stall',
        'bronzong-klinklang': 'Metal Box Klingklang',
        'blank-kyogre-primal': 'Primal Kyogre',
        'landorus-therian-raichu': 'Landorus Raichu',
        'manectric-mega-garbodor': 'Mega Manectric',
        'blank-hippowdon': 'Hippowdon',
        'keldeo-resolute-blastoise': 'ArchieStoise',
        'flareon-empoleon': 'Flareon',
        'yveltal-garbodor': 'Yveltal Garbodor',
        'gengar-trevenant': 'Trevenant Gengar',
        'bunnelby-slurpuff': 'Bunnelby Mill',
        'groudon-primal-lucario-mega': 'Primal Groudon',
        'snorlax-suicune': 'Wall Stall',
        'manectric-mega-empoleon': 'Mega Manectric',
    },
    '2014': {
        'yveltal-darkrai': 'Yveltal',
        'yveltal-garbodor': 'Yveltal Garbodor',
        'virizion-genesect': 'VirGen',
        'kyurem-deoxys': 'TDK',
        'flygon-dusknoir': 'Flygon',
        'lugia-deoxys': 'Plasma Lugia',
        'weavile-lopunny': 'Weavile Lopunny',
        'blank-pyroar': 'Pyroar',
        'landorus-therian-raichu': 'Landorus Raichu',
        'yveltal-raticate': 'Yveltal',
        'blastoise-keldeo-resolute': 'Keldeo Blastoise',
        'empoleon-dusknoir': 'Empoleon',
        'aromatisse-deoxys': 'Fairy Box',
        'blank-ninetales': 'Ninetales',
        'kangaskhan-aromatisse': 'Mega Kangaskhan',
        'yveltal-dusknoir': 'Yveltal Dusknoir',
        'accelgor-trevenant': 'Accelgor Trevenant',
        'toxicroak-landorus-therian': 'Toxic Haymaker',
        'yveltal-raichu': 'Yveltal Raichu',
        'blank-yveltal': 'Yveltal',
        'virizion-raichu': 'VirGen Raichu',
      
    },
    '2013': {
        'kyurem-deoxys': 'TDK',
        'blastoise-keldeo-resolute': 'Keldeo Blastoise',
        'blank-klinklang': 'Klinklang',
        'darkrai-sableye': 'Darkrai-EX',
        'rayquaza-eelektrik': 'RayEels',
        'lugia-deoxys': 'Plasma Lugia',
        'sableye-garbodor': 'Sableye Garbodor',
        'darkrai-garbodor': 'Darkrai Garbodor',
        'blank-flareon': 'Flareon',
        'accelgor-gothitelle': "Accelgor Gothitelle",
        'terrakion-garbodor': "Terrakion Garbodor",
        'lugia-cofagrigus': "Plasma Lugia",
        'blank-darkrai': "Darkrai-EX",
        'thundurus-therian-deoxys': 'Plasma',
        'landorus-therian-garbodor': 'Landorus Garbodor',
        'blank-garbodor': 'Garbodor',
        'darkrai-mewtwo': 'Darkrai Mewtwo',
        'darkrai-terrakion': 'Darkrai Terrakion',
        'zekrom-eelektrik': 'ZekEels',
        'blank-ho-oh': 'Ho-Oh-EX',
        'garchomp-altaria': 'Garchomp Altaria',
    },
    '2012': {
        'darkrai-mewtwo': 'Darkrai Mewtwo',
        'blank-darkrai': 'Darkrai-EX',
        'celebi-mewtwo': 'CMT',
        'chandelure-accelgor': 'Chandygor',
        'mewtwo-eelektrik': 'Mewtwo Eels',
        'magnezone-emboar': 'MagneBoar',
        'mewtwo-terrakion': 'Mewtwo Terrakion',
        'zekrom-eelektrik': 'ZekEels',
        'terrakion-eelektrik': 'Terrakion Eels',
        'tornadus-eelektrik': 'Tornadus Eels',
        'scizor-vileplume': 'Scizor Vileplume',
        'blank-klinklang': 'Klinklang',
        'mismagius-vileplume': 'Mismagius Vileplume',
        'darkrai-unown-a': 'Darkrai-EX',
        'vanilluxe-vileplume': 'VVV',
        'blank-kyurem': 'Kyurem',
        'landorus-terrakion': 'Landorus Terrakion',
        'darkrai-sableye': 'Darkrai-EX',
    },
    '2011': {
        'reshiram-typhlosion': 'Reshiphlosion',
        'yanmega-magnezone': 'Yanmega Magnezone',
        'donphan-zoroark': "Stage 1's",
        'magnezone-emboar': 'MagneBoar',
        'vileplume-reuniclus': 'The Truth',
        'kingdra-yanmega': 'Kingdra Yanmega',
        'yanmega-zoroark': "Stage 1's",
        'mew-vileplume': 'Mew Box',
        'reshiram-emboar': 'ReshiBoar',
        'tyranitar-serperior': 'Tyranitar Serperior',
        'mew-yanmega': 'Mew Box',
        'yanmega-vileplume': 'Yanmega PRIME',
        'yanmega-zekrom': 'Yanmega PRIME',
        'donphan-machamp': 'Donphan Machamp',
        'ursaring-vileplume': 'Bear Hug',
    },
    '2010': {
        'luxray-garchomp': 'LuxChomp',
        'luxray-roserade': 'SP Box',
        'gardevoir-gallade': 'Gardevoir Gallade',
        'dialga-garchomp': 'DialgaChomp',
        'blank-gengar': 'Gengar',
        'blank-jumpluff': 'Jumpluff',
        'flygon-torterra': 'FlyTerra',
        'blank-arceus': 'Arceus',
        'blank-regigigas': 'Regigigas',
        'steelix-blissey': 'Steelix PRIME',
        'blank-donphan': 'Donphan PRIME',
        'blank-gyarados': 'Gyarados',
        'kingdra-donphan': 'Kingdra PRIME',
        'abomasnow-ampharos': 'Abomasnow Ampharos',
        'sableye-blaziken': 'ChenLock',
        'sableye-garchomp': 'SableLock',
        'garchomp-dusknoir': 'Garchomp SV',
        'gengar-garchomp': 'Gengar C (Garchomp)',
        'blank-shuppet': 'Shuppet Donk',
        'blank-tyranitar': 'Tyranitar PRIME',
        'tyranitar-machamp': 'Tyranitar PRIME',
        'kingdra-machamp': 'Kingdra Machamp',
        'blank-machamp': 'Machamp',
        'blank-garchomp': 'Garchomp SV',
        'palkia-mesprit': 'Palkia Lock',
        'flygon-machamp': 'Flygon Machamp',
        'blank-palkia': 'Palkia Lock',
        'blaziken-garchomp': 'BlazeChomp',
        'blank-gliscor': 'Gliscor',
        'gliscor-spiritomb': 'Gliscor',
        'donphan-entei-raikou': 'Donphan PRIME',
        'gengar-machamp': 'Gengar Machamp',
        'gardevoir-azelf': 'Gardevoir AMU',
        'luxray-blaziken': 'LuxChomp',
    },
    '2009': {
        'blank-gengar': 'Gengar',
        'gengar-nidoqueen': 'QueenGar',
        'blank-palkia': 'Palkia Lock',
        'flygon-machamp': 'Flygon Machamp',
        'flygon-weavile': 'Flygon Weavile',
        'honchkrow-toxicroak': 'SP Box',
        'blank-gyarados': 'Gyarados',
        'flygon-palkia': 'Flygon Lock (Stallgon)',
        'palkia-luxray': 'Palkia Lock',
        'beedrill-luxray': 'Beedrill (LuxDrill)',
        'gengar-dusknoir': 'Gengar Dusknoir',
        'luxray-infernape': 'LuxApe',
        'dialga-palkia': 'Dialga Palkia (DPL)',
        'machamp-lumineon': 'Machamp',
        'luxray-manectric': 'Luxray Manectric',
        'blank-flygon': 'Flygon',
        'gengar-machamp': 'Gengar Machamp',
        'blank-beedrill': 'Beedrill (Speedrill)',
        'luxray-toxicroak': 'SP Box',
        'gengar-starmie': 'Gengar',
        'blank-kingdra': 'Kingdra',
        'kingdra-flygon': 'Kingdra',
        'blank-dialga': 'Dialga',
        'dialga-gallade': 'Dialga',
        'flygon-nidoqueen': 'Flygon',
        'gardevoir-gallade': 'Gardevoir Gallade',
        'blank-machamp': 'Machamp',
    },
    '2008': {
        'gardevoir-gallade': 'Gardevoir Gallade',
        'empoleon-bronzong': 'Empoleon',
        'blank-blissey': 'Blissey',
        'empoleon-omastar': 'Empoleon',
        'ampharos-bronzong': 'Ampharos Bronzong',
        'banette-blissey': 'Banette Blissey',
        'glaceon-absol': 'Glaceon Lock',
        'magmortar-leafeon': 'Magmortar Leafeon',
        'honchkrow-palkia': 'Honchkrow',
        'scizor-toxicroak': 'Scizor',
        'blank-eevee': 'Eeveelutions',
        'blank-empoleon': 'Empoleon',
        'scizor-electrode': 'Scizor',
        'magnezone-leafeon': 'Magnezone Leafeon',
        'torterra-sceptile': 'Torterra',
        'absol-gallade': 'Gallade Lock',
        'blank-eevee-no-heart': 'Eeveelutions',
    },
    '2007': {
        'absol-eevee-no-heart': 'Absolutions',
        'flygon-exeggutor': 'R-Gon',
        'blank-empoleon': 'Empoleon',
        'banette-vaporeon': 'Banette Eeveelutions',
        'flygon-magcargo': 'Flygon',
        'lucario-eevee-no-heart': 'Lucario Eeveelutions',
        'empoleon-raichu': 'Empoleon',
        'flygon-delcatty': 'Flygon',
        'blank-scizor': 'Scizor',
        'electivire-dragonite': 'Electivire',
        'banette-lucario': 'Banette',
        'blank-lucario': 'Lucario',
        'banette-solrock': 'Banette',
        'infernape-delcatty': 'Infernape Delcatty',
        'blank-rhyperior': 'Rhyperior',
        'blank-kingdra': 'Kingdra',
        'blank-banette': 'Banette',
        'metagross-dragonite': 'Metanite',
        'flareon-ariados': 'Flariados',
        'empoleon-marowak': 'Empoleon (Ambush)',
        'metagross-meganium': 'Metanium',
        'flygon-eevee-no-heart': 'FlyVees',
        'sceptile-metagross': 'Sceptile Metagross',
        'blank-machamp': 'Machamp',
        'medicham-banette': 'Medicham Banette',
        'lucario-machamp': 'Lucario Machamp',
        'scizor-metagross': 'Scizor Metagross',
        'blank-rayquaza': 'Robquaza',
        'raichu-kingler': 'Riachu Kingler',
        'blank-flygon': 'Flygon',
        'latias-latios': 'Latias Latios',
        'banette-eevee-no-heart': 'Banette Eeveelutions',
        'raichu-exeggutor': 'RaiEggs',
        'blank-shiftry': 'Shiftry',
        'empoleon-eevee-no-heart': 'Empoleon',
    },
    '2006': {
        'lugia-blastoise': 'LBS',
        'metagross-dragonite': 'Metanite',
        'tyranitar-electrode': 'BombTar',
        'mew-manectric': 'Mewtric',
        'eevee-no-heart-pidgeot': 'Eeveelutions',
        'dragonite-electrode': 'DragTrode',
        'ludicolo-magcargo': 'LudiCargo',
        'blank-arcanine': 'Arcanine',
        'nidoqueen-houndoom': 'Nidoqueen',
        'tyranitar-ampharos': 'Rock Lock',
        'flareon-ariados': 'Flariados',
        'banette-medicham': 'Banette Medicham',
        'blank-machamp': 'Machamp',
        'blank-nidoqueen': 'Nidoqueen',
        'raichu-exeggutor': "RaiEggs",
        'lunatone-solrock': "Lunatone Solrock",
        'exeggutor-electrode': "Scrambled Eggs",
        'arcanine-eevee-no-heart': "Arcanine",
        'blank-flygon': 'Flygon',
        'blastoise-mew': "LBS",
        'nidoqueen-nidoking': "Nidoqueen",
        'kingdra-pidgeot': "Kingdra",
        'mew-jynx': "Mew Lock",
        'blank-shedinja': "Shedinja",
        'metagross-electrode': "Metagross Electrode",
        'blank-politoed': "Politoed Stall",
        'blank-weezing': "Weezing",
        'medicham-houndoom': 'Medicham',
        'arcanine-ninetales': 'Arcanine',
        'dustox-houndoom': 'Dustox Houndoom',
        'azumarill-crobat': 'Azumarill Crobat',
        'eevee-pidgeot': 'Eeveelutions',
    },
    '2005': {
        'ludicolo-magcargo': 'LudiCargo',
        'zapdos-rayquaza': 'ZRE',
        'blank-medicham': 'Medicham',
        'tyranitar-ampharos': 'Rock Lock',
        'blank-steelix': 'Dark Steelix',
        'blank-nidoqueen': 'Nidoqueen (Queendom)',
        'blank-sharpedo': 'Sharpedo',
        'tyranitar-electrode': 'PowTar',
        'tyranitar-magcargo': 'Dark Tyranitar',
        'medicham-ninetales': 'Medicham',
        'blank-blaziken': 'Blaziken',
        'delcatty-electrode': 'Delcatty Electrode',
        'ludicolo-grumpig': 'Ludicolo Grumpig',
        'moltres-zapdos': 'Moltres Zapdos',
        'slowking-magcargo': 'Slowking',
        'machamp-pidgeot': 'Machamp',
        'blastoise-deoxys': 'Blastoise',
        'medicham': 'Medicham',
        'tyranitar-pidgeot': 'Dark Tyranitar',
        'swampert-articuno': 'Swampert',
        'blank-vileplume': 'Vileplume',
        'zapdos-electrike': 'ZapTurnDos',
        'dragonite-electrode': 'DragTrode',
        'blank-metagross': 'Metagross',
        'hariyama-medicham': 'Hariyama Lock',
        'blank-tyranitar': 'Dark Tyranitar',
        'blank-groudon': "Magma's Groudon",
        'blank-slowking': 'Dark Slowking',
        'slaking-salamence': 'Slaking',
    },
    '2004': {
        'blank-groudon': "Magma's Groudon",
        'blank-blaziken': 'Blaziken',
        'blank-shiftry': 'Shiftry',
        'blank-gardevoir': 'Gardevoir',
        'crobat-gorebyss': 'Crobat Gorebyss',
        'medicham-lanturn': 'Medicham',
        'blank-wailord': 'Wailord',
        'walrein-milotic': 'Walrein',
        'kyogre-manectric': 'Team Aqua',
        'jumpluff-gorebyss': 'Jumpluff Gorebyss',
        'sceptile-muk': 'Sceptile',
        'medicham-banette': 'Medicham',
        'gardevoir-claydol': 'Gardevoir',
        'mewtwo-gorebyss': 'Thundercatz',
        'blank-swampert': 'Swampert',
        'blank-machamp': 'Machamp',
        'gardevoir-gorebyss': 'Gardevoir',
        'walrein-arcanine': 'Walrein',
        'blank-gorebyss': 'Gorebyss',
        'blank-metagross': 'Metagross',
        'ampharos-slaking': 'Ampharos Slaking',
        'kyogre-walrein': 'Team Aqua',
        'gardevoir-metagross': 'Gardevoir',
        'blank-kingdra': 'Kingdra',
        'blaziken-rayquaza': 'Blaziken',
        'blaziken-salamence': 'Blaziken',
        'blank-lanturn': 'Lanturn',
        'blank-exploud': 'Exploud',
        'blaziken-ninetales': 'Blaziken',
        'metagross-gorebyss': 'Metagross Gorebyss',
        'gardevoir-milotic': 'Gardevoir',
        'metagross-wobbuffet': 'Metagross',
        'ampharos-lanturn': 'Ampharos',
        'shiftry-delcatty': 'Shiftry',
        'gorebyss-starmie': 'Gorebyss',
        'sceptile-milotic': 'Sceptile',
        'walrein-wigglytuff': 'Walrein',
        'blaziken-gardevoir': 'Blaziken',
        'salamence-metagross': 'Salamence',
        'shiftry-ninetales': 'Shiftry',
        'muk-wobbuffet': 'Muk',
        'machamp-aggron': 'Machamp',
    },
    '2003': {
        'eeee': '',

    },
    '2002': {
        'feraligatr-slowking': 'Dark Feraligatr',
        'espeon-slowking': 'Espeon',
        'blank-blastoise': 'Dark Blastoise',
        'blank-kingdra': 'Kingdra',
        'blank-feraligatr': 'Dark Feraligatr',
        'donphan-slowking': 'Donphan',
        'blank-tyranitar': 'Tyranitar',
        'kingdra-steelix': 'Kingdra',
        'lanturn-slowking': 'Lanturn',
        'kingdra-slowking': 'Kingdra',
        'blastoise-slowking': 'Dark Blastoise',
        'feraligatr-parasect': 'Dark Feraligatr',
        'espeon-umbreon': 'Espeon',
        'steelix-gyarados': 'Steelix Gyarados',
        'blank-zapdos': "Rocket's Zapdos",
        'sneasel-slowking': 'Sneasel',
        'blank-riptide': 'Riptide Feraligatr',
        'blank-chansey': 'Chansey',
        'sneasel-wigglytuff': 'Sneasel',
        'blank-clefable': 'Clefable',
        'chansey-slowking': 'Chansey',
        'kingdra-muk': 'Kingdra',
        'espeon-kingdra': 'Espeon',
        'ninetales-steelix': 'Shapeshift Ninetales',
        'blank-gengar': 'Gengar',
        'blank-blissey': 'Blissey',
        'blank-charizard': 'Charizard',
        'typhlosion-arcanine': 'Typhlosion',
        'entei-magcargo': 'EnteiCargo',
        'blastoise-steelix': 'Dark Blastoise',
        'charizard-slowking': 'Charizard',
        'ampharos-raichu': 'Ampharos',
        'typhlosion-moltres': 'Typhlosion',
        'blank-ampharos': 'Ampharos',
        'blank-ampharos': 'Ampharos',
        'golduck-slowking': 'Golduck',
        'kingdra-murkrow': 'Kingdra',
        'blank-muk': 'Dark Muk',
        'meganium-heracross': 'Meganium',
        'blank-crobat': 'Crobat',
        'steelix-umbreon': 'Steelix',
        'blank-victreebel': 'Victreebel',
        'typhlosion-magcargo': 'Typhlosion',
        'blank-umbreon': 'Umbreon',
        'kingdra-espeon': 'Kingdra',
        'crobat-piloswine': 'Crobat',
        'victreebel-umbreon': 'Victreebel',
        'hitmonchan-scyther': "Rocket's Hitmonchan Scyther",
        'tyranitar-slowking': 'Tyranitar',
        'kingdra-umbreon': 'Kingdra',
        'steelix-slowking': 'Steelix',
        'gengar-golduck': 'Gengar Golduck',
    },
    '2001': {
        'blank-feraligatr': 'Riptide Feraligatr',
        'crobat-murkrow': 'Crobat',
        'feraligatr-qwilfish': 'Riptide Feraligatr',
        'steelix-slowking': 'Steelix',
        'arcanine-entei': 'Arcanine',
        'typhlosion-arcanine': 'Typhlosion',
        'typhlosion-houndoom': 'Typhlosion',
        'steelix-hitmonchan': 'Steelix',
        'steelix-slowking': 'Steelix',
        'crobat-umbreon': 'Crobat',
        'feraligatr-suicune': 'Riptide Feraligatr',
        'blank-crobat': 'Crobat',
        'sandslash-muk': 'Sandslash',
        'slowking-umbreon': 'Slowking',
        'raichu-umbreon': 'Raichu',
        'entei-magcargo': 'EnteiCargo',
        'ampharos-zapdos': 'Ampharos',
        'blank-victreebel': 'Victreebel',
        'slowking-suicune': 'Slowking',
        'arcanine-ho-oh': 'Arcanine',
        'slowking-golduck': 'Slowking',
        'blastoise-steelix': 'Blastoise Steelix',
        'blank-arcanine': 'Arcanine',
        'sandslash-dugtrio': 'Sandslash Dugtrio',
        'typhlosion-charizard': 'Typhlosion',
        'steelix-slowking': 'Steelix',
        'blank-dewgong': 'Dewgong',
        'steelix-zapdos': 'Steelix',
        'arcanine-slowking': 'Arcanine',
        'arcanine-rapidash': 'Arcanine',
        'slowking-sneasel': 'Slowking Sneasel',
        'blank-zapdos': 'Zapdos',
        'zapdos-steelix': 'Zapdos',
        'blank-wigglytuff': 'Wigglytuff',
        'blastoise-feraligatr': 'Rain Dance',
    },
    '2000': {
        'blastoise-articuno': 'Rain Dance',
        'hitmonchan-magmar': 'Haymaker',
        'clefable-wigglytuff': 'Clefable Wigglytuff',
        'wigglytuff-zapdos': 'Wigglytuff',
        'wigglytuff-hitmonchan': 'Wigglytuff',
        'wigglytuff-dodrio': 'Wigglytuff',
        'hitmonchan-zapdos': 'Haymaker',
        'hitmonchan-sandslash' : 'Hitmonchan Sandslash',
        'hitmonchan-dodrio' : 'Haymaker',
        'wigglytuff-magmar' : 'Wigglytuff',
        'blastoise-wigglytuff' : 'Rain Dance',
        'magmar-arcanine' : 'Haymaker',
        'clefable-hitmonchan': 'Clefable',
        'aerodactyl-hitmonchan': 'Haymaker',
        'venusaur-kangaskhan': 'Venusaur',
        'hitmonchan-mewtwo': 'Haymaker',
        'wigglytuff-mewtwo': 'Wigglytuff',
        'hitmonchan-electabuzz': 'Haymaker',
        'wigglytuff-electabuzz': 'Wigglytuff',
        'mewtwo-electabuzz': 'Haymaker',
        'wigglytuff-scyther': 'Wigglytuff',
        'mr-mime-electabuzz': 'Mr. Mime',
        'articuno-hitmonchan': 'Haymaker Articuno',
        'primeape-dewgong': 'Fighting Water',
        'electrode-charmander': 'Lightning Fire',
        'dugtrio-exeggutor': 'Fighting Grass',
        'mr-mime-onix': 'Psychic Fighting',
    },
    '1999': {
        'lickitung-scyther': 'Lickitung Stall',
        'wigglytuff-hitmonchan': 'Wigglytuff',
        'lickitung-moltres': 'Lickitung Stall',
        'electabuzz-magmar': 'Haymaker',
        'mewtwo-chansey': 'Mewtwo',
        'lickitung-magmar': 'Lickitung Stall',
        'blastoise-articuno': 'Rain Dance',
        'blank-dodrio': 'Dodrio',
        'blank-wigglytuff': 'Wigglytuff',
    },
};

const getCustomLabel = (eventId, sprite1, sprite2) => {
    let eventYearKey = '';
    if (eventId.includes('1999')) {
      eventYearKey = '1999';
    } else if (eventId.includes('2000')) {
      eventYearKey = '2000';
    } else if (eventId.includes('2001')) {
      eventYearKey = '2001';
    } else if (eventId.includes('2002')) {
      eventYearKey = '2002';
    } else if (eventId.includes('2003')) {
      eventYearKey = '2003';
    } else if (eventId.includes('2004')) {
      eventYearKey = '2004';
    } else if (eventId.includes('2005')) {
      eventYearKey = '2005';
    } else if (eventId.includes('2006')) {
      eventYearKey = '2006';
    } else if (eventId.includes('2007')) {
      eventYearKey = '2007';
    } else if (eventId.includes('2008')) {
      eventYearKey = '2008';
    } else if (eventId.includes('2009')) {
      eventYearKey = '2009';
    } else if (eventId.includes('2010')) {
      eventYearKey = '2010';
    } else if (eventId.includes('2011')) {
        eventYearKey = '2011';
    } else if (eventId.includes('2012')) {
        eventYearKey = '2012';
    } else if (eventId.includes('2013')) {
        eventYearKey = '2013';
    } else if (eventId.includes('2014')) {
        eventYearKey = '2014';
    } else if (eventId.includes('2015')) {
        eventYearKey = '2015';
    } else if (eventId.includes('2016')) {
        eventYearKey = '2016';
    } else if (eventId.includes('2017')) {
        eventYearKey = '2017';
    } else if (eventId.includes('2018')) {
        eventYearKey = '2018';
    } else if (eventId.includes('2019')) {
        eventYearKey = '2019';
    } else if (eventId.includes('2020')) {
        eventYearKey = '2020';
    } else if (eventId.includes('2021')) {
        eventYearKey = '2021';
    } else if (eventId.includes('2022')) {
        eventYearKey = '2022';
    } else if (eventId.includes('2023')) {
        eventYearKey = '2023';
    } else if (eventId.includes('2024')) {
    eventYearKey = '2024';
    } else if (eventId.includes('2025')) {
    eventYearKey = '2025';
    } else if (eventId.includes('2026')) {
    eventYearKey = '2026';
    }
const eventLabels = customLabelsConfig[eventYearKey];
  // always fall back to ‘blank’ if sprite1 is empty
  const key = `${sprite1 || 'blank'}-${sprite2}`;
  if (eventLabels) {
    return eventLabels[key] || key;
  }
  return key;
};

export { getCustomLabel };
